[project]
name = "api"
version = "0.1.0"
description = "An API Server using FastAPI"
requires-python = ">=3.10"
dependencies = [
    "uvicorn>=0.27.1",
    "fastapi[standard]>=0.115.4",
    "core",
]

[tool.uv]
package = false
